language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install ".[test]" . # install package + test dependencies
# command to run tests
script:
  - pytest
